### ISSUE TITLE
Controller example?

### ISSUE THREAD

**Issue by xguerin** [microbean/microbean-kubernetes-controller#11]
Hello,

Nice project. Have you considered adding a simple usage example for the Controller?

Thanks,

**Comment by ljnelson** [comment]
Early days; _definitely_ on my TODO list.  You might be interested in [looking at the test code in the related microbean-kubernetes-controller-cdi project](https://github.com/microbean/microbean-kubernetes-controller-cdi/blob/master/src/test/java/org/microbean/kubernetes/controller/cdi/TestEventDistribution.java#L80-L94).

**Comment by xguerin** [comment]
Thanks. The interface is actually straightforward enough to allow me to cook something up pretty easily to watch CRDs. Pretty nice implementation and blog post BTW 👍

**Comment by ljnelson** [comment]
Yes, in general (and you've probably already figured this out), you want a `Controller` that was created with a [`ResourceTrackingEventQueueConsumer`](https://github.com/microbean/microbean-kubernetes-controller/blob/9e26badc3b1d85b6876d04f9db6a6cd91a33e233/src/main/java/org/microbean/kubernetes/controller/ResourceTrackingEventQueueConsumer.java#L105).  I'd be interested to hear if you get it working.

**Comment by xguerin** [comment]
Thanks for the pointer. I replaced my basic lambdas with an extension of that class and it works so far.
