### ISSUE TITLE
Event resource delta

### ISSUE THREAD

**Issue by xguerin** [microbean/microbean-kubernetes-controller#12]
Hey there,

What is the best way to get the resource delta on a modification event? I seem to recall something about delta queues in your blog but I am not entirely convinced this is related.

Thanks,

**Comment by ljnelson** [comment]
Oh, I see.  You are asking a general question, then: given two Kubernetes resources represented as `HasMetadata` objects, how can you diff them?  That's a kubernetes-client question, and it seems they use this: https://github.com/fabric8io/kubernetes-client/blob/59e5b9d0f318f4f78f417efaec34050ed8122b8f/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L39

**Comment by xguerin** [comment]
thanks for the pointer 👍
