### ISSUE TITLE
Custom resource controller with `withLabel` filter not filtering resources

### ISSUE THREAD

**Issue by xguerin** [microbean/microbean-kubernetes-controller#16]
Hello there, 

I am not sure if it's a client library issue or a controller issue, but when creating a controller for a custom resource, it looks like the ~`.withFilter()`~ `.withLabel()` constraint is not respected.

The following example would trigger the `onAddition` callback on every pod in namespace `ns` regardless of the labels:

```java
controller = new Controller<>(
    client.customResources(this.crd, CRD.class, CRDList.class, DoneableCRD.class)
          .inNamespace(ns)
          .withLabel("label", "hello"),
    new GenericEventQueueConsumer<>(new HashMap<>(), this));
```

The namespace filter, on the other hand, is respected. Interestingly, when calling the client function outside the controller, the filtering seems to work:

```java
client.customResources(this.crd, CRD.class, CRDList.class, DoneableCRD.class)
      .inNamespace(ns)
      .withLabel("label", "hello")
      .list()
      .getItems();
-> []
```

Any idea? If it's a client issue I'll be happy to follow up with them.

Thanks,

**Comment by ljnelson** [comment]
(There is no `withFilter()` method that I know of; I assume that's just a typo and you meant `withLabel()`.)

All I do in the controller, really, is call `list()` and `getItems()` once you boil everything else away.  If you're using the latest _released_ version, and not the snapshot you were perhaps testing earlier, it is conceivable that some of the egregious hacks I put in to make CRDs work are failing in some way&mdash;but I'd expect an error in that case.

**Comment by xguerin** [comment]
Ah yes, sorry, I mean `withLabel`. That was indeed with the latest release, not the snapshot. I am trying now with the updated libs.

**Comment by xguerin** [comment]
Yeah, no dice with the `0.2.3-SNAPSHOT` and version `4.1.1` of the client. I'll post an issue on the client side.

**Comment by ljnelson** [comment]
I'm guessing it's an issue here if it works outside of the controller framework.  I'll classify this issue as a bug and look into it.

**Comment by xguerin** [comment]
I'm gonna try to reproduce the problem with a bare bone `Watcher` and I'll let you know.

**Comment by ljnelson** [comment]
I've had a quick look, but can't see where I'm doing anything obviously wrong.  As I suspected, I'm basically taking the "operation" in and calling `list()` on it:

https://github.com/microbean/microbean-kubernetes-controller/blob/38a46e12da34cca012bc5fd9bb5b5dcc81da9a3f/src/main/java/org/microbean/kubernetes/controller/Reflector.java#L832

Now, I _am_ using the `withResourceVersion("0")` "filter":

https://github.com/microbean/microbean-kubernetes-controller/blob/38a46e12da34cca012bc5fd9bb5b5dcc81da9a3f/src/main/java/org/microbean/kubernetes/controller/Reflector.java#L413

Maybe that has something to do with it?

**Comment by xguerin** [comment]
Intriguing. So with the bare bone watcher, it behaves as expected. I simply took the `WatchExample` from [here](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/WatchExample.java). CRD that don't have the label don't get any events while CRD that have the labels do. Let me gist you the complete code and edit this comment.

**Comment by xguerin** [comment]
Yeah, I just added `withResourceVersion` to my example, and it cancels the `withLabel` call.

**Comment by ljnelson** [comment]
Well _that_ sucks.  Unless I'm missing something awful, that sounds very much like a bad bug in the fabric8 library.  I'll double-check the javadocs (ho ho) to make sure.

**Comment by ljnelson** [comment]
Hmm; I do wonder if perhaps since technically this is a modification of the original operation I need more of a "copy the whole thing as it exists and then bolt `withResourceVersion()` onto it" kind of workflow here.

But I have tests that show this working with built in objects, I think, so perhaps this is another CRD oddity?  I'd be curious if your gist would exhibit the same behavior if it listed and watched, say, `Pod`s or `ConfigMap`s instead of CRDs.

**Comment by xguerin** [comment]
> But I have tests that show this working with built in objects, I think, so perhaps this is another CRD oddity?

Yeah it is. I have other examples of label filtering working perfectly well for pods, for instance.

**Comment by xguerin** [comment]
Also, re: the source for `withResourceVersion`, labels are passed down to the new object so my original theory does not hold. It might very well be a bug with the control path down the line.

**Comment by xguerin** [comment]
So it's definitely a bug in the client library: [CustomResourceOperationsImpl](https://github.com/fabric8io/kubernetes-client/blob/a7b5fa28388d7dfbf418bc58226acc2e0885e029/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java#L126) override the `withResourceVersion` method and returns a new `CustomResourceOperationsImpl` without using a `HasMetadataOperation` construction that accepts labels, etc.

The fix should be pretty straightforward. I'm gonna take a shot at it and see if that helps. Thanks for the insight!

**Comment by ljnelson** [comment]
OK; do watch out as I think there's a pull request open in that project that would do away with any hand-tooled classes related to CRDs…https://github.com/fabric8io/kubernetes-client/pull/1346

**Comment by xguerin** [comment]
Thanks for letting me know, although I don't think there is any conflict. Here is the proposed patch: https://github.com/fabric8io/kubernetes-client/pull/1425.

**Comment by xguerin** [comment]
Merged.
