### ISSUE TITLE
Release 0.2.3

### ISSUE THREAD

**Issue by xguerin** [microbean/microbean-kubernetes-controller#19]
Hello,

The 0.2.3 release has been in SNAPSHOT mode for a while now. Would it make sense to release it?

Thanks !

**Comment by ljnelson** [comment]
Hello; it might!  It's just me so sometimes these things take a while.  I will look into it.

**Comment by xguerin** [comment]
Let me know if I can help in any way :)

**Comment by ljnelson** [comment]
Thanks for the offer.  I'll try to take care of it this weekend.

In the meantime, if you're just looking to do something like update third-party dependencies, you should be able to do that in your own `pom.xml`'s `<dependencyManagement>` section.

**Comment by ljnelson** [comment]
Hello; I've updated the project to use the latest compatible dependencies.  This puts it on Fabric8's Kubernetes Client version 4.11.1.  I've uploaded version 0.3.0-SNAPSHOT to Sonatype's snapshot repository.  Would you mind giving it a quick test to see if it will meet your needs?  If so, I'll release it shortly thereafter.

**Comment by xguerin** [comment]
Absolutely. I’ll take care of it tomorrow.

**Comment by xguerin** [comment]
All good on my end 👍 It took me some time to bring my CRD controllers up to speed with the changes introduced in v1.19.

**Comment by ljnelson** [comment]
[Released](https://search.maven.org/classic/#artifactdetails%7Corg.microbean%7Cmicrobean-kubernetes-controller%7C0.3.0%7Cjar).
